In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
pd.set_option("display.width", 400)

In [3]:
path = Path("../data/train_val.npy")
arr = np.load(path, allow_pickle=True)
df = pd.DataFrame(arr)
df.columns = ["filename", "class", "box"]
df.head()

           filename         class                                                box
0  DJI_0619_018.JPG       [house]  [[0.1488970588235294, 0.8033088235294118, 0.38...
1  DJI_0619_027.JPG        [road]  [[0.5110294117647058, 0.1488970588235294, 0.90...
2  DJI_0619_028.JPG  [pole, pole]  [[0.06066176470588235, 0.2426470588235294, 0.1...
3  DJI_0619_029.JPG        [pole]  [[0.31066176470588236, 0.4889705882352941, 0.3...
4  DJI_0619_033.JPG        [road]  [[0.16727941176470587, 0.6286764705882353, 0.9...

In [4]:
df = df.explode("class").explode("box", ignore_index=True)
df.head()

           filename  class                                                box
0  DJI_0619_018.JPG  house  [0.1488970588235294, 0.8033088235294118, 0.386...
1  DJI_0619_027.JPG   road  [0.5110294117647058, 0.1488970588235294, 0.909...
2  DJI_0619_028.JPG   pole  [0.06066176470588235, 0.2426470588235294, 0.11...
3  DJI_0619_028.JPG   pole  [0.8511029411764706, 0.47058823529411764, 0.93...
4  DJI_0619_028.JPG   pole  [0.06066176470588235, 0.2426470588235294, 0.11...

In [5]:
box = pd.DataFrame(df["box"].tolist())
box.columns = ["xmin", "ymin", "xmax", "ymax"]
box.head()

       xmin      ymin      xmax      ymax
0  0.148897  0.803309  0.386029  0.987132
1  0.511029  0.148897  0.909926  0.262868
2  0.060662  0.242647  0.113971  0.336397
3  0.851103  0.470588  0.933824  0.586397
4  0.060662  0.242647  0.113971  0.336397

In [6]:
df = pd.concat([df.loc[:, "filename":"class"], box], axis=1)
df.head()

           filename  class      xmin      ymin      xmax      ymax
0  DJI_0619_018.JPG  house  0.148897  0.803309  0.386029  0.987132
1  DJI_0619_027.JPG   road  0.511029  0.148897  0.909926  0.262868
2  DJI_0619_028.JPG   pole  0.060662  0.242647  0.113971  0.336397
3  DJI_0619_028.JPG   pole  0.851103  0.470588  0.933824  0.586397
4  DJI_0619_028.JPG   pole  0.060662  0.242647  0.113971  0.336397